### ISSUE TITLE
As a customer, I want illustrated "About Me" page provides a clear and engaging introduction, offering visual context to the story behind the brand

### ISSUE THREAD

**Issue by Annabell-prog** [Annabell-prog/hobiprojekt#12]
- [ ] The main menu has a new element "About Me" .When the browser is on the about me page, it is 
       highlighted
- [ ] Photos of the creator and their work are displayed for visual reference
- [ ] A biography section provides details about the creator’s journey and work
![ab me](https://github.com/user-attachments/assets/993f5b52-4454-490b-9045-b4b56825efe7)

**Comment by OveKre** [comment]
1. The "About Me" link appears in the main menu and becomes highlighted when the user is on the page
2. High-quality images of the creator and their work are included on the "About Me" page. These images are responsive and scale properly on all devices
3. A biography section is included, presenting a brief overview of the creator’s background and achievements
