### ISSUE TITLE
As a customer, I want a clear and simple HOME page, so I can easily find the main sections of the site

### ISSUE THREAD

**Issue by Annabell-prog** [Annabell-prog/hobiprojekt#2]
- [ ] The main menu has a new element "Home" . When the browser is on the home page, it is 
        highlighted
- [ ] The brand name "Lyzell's Pottery" is prominently displayed at the top of the page
- [ ] The Instagram logo is visible and functional, directing the user to the correct Instagram profile so user can easily view 
       the pottery collection
- [ ] The Facebook logo is visible and functional, directing the user to the correct Facebook page so the user can see  the 
       pottery collection's profile
- [ ] The images are responsive and displayed without distortion, showcasing different pottery pieces. Clicking on the images 
        leads to the detailed page about the pieces
- [ ] A welcoming text provides an introduction and overview of the website's content and purpose

![home ](https://github.com/user-attachments/assets/8c611e92-45f0-4e33-a441-a076b7c6bc33)

**Comment by Annabell-prog** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lyzell'i Keraamikakoda</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 0;
            margin: 0;
        }
        header {
            text-align: center;
            padding: 20px;
            background-color: #f2f2f2;
        }
        .language-buttons {
            margin-top: 10px;
        }
        .horizontal-menu {
            display: flex;
            justify-content: center;
            padding: 10px;
            background-color: #333;
        }
        .horizontal-menu a {
            color: white;
            text-decoration: none;
            padding: 10px 20px;
        }
        .horizontal-menu a:hover {
            background-color: #575757;
        }
        .pictures {
            display: flex;
            justify-content: space-around;
            margin: 20px;
        }
        .pictures img {
            width: 30%;
            border: 2px solid #ddd;
            padding: 10px;
        }
        .chat-box {
            position: fixed;
            bottom: 20px;
            right: 20px;
            width: 300px;
            height: 400px;
            background-color: #f1f1f1;
            border: 1px solid #ccc;
            border-radius: 10px;
            padding: 10px;
        }
        footer {
            text-align: center;
            background-color: #f2f2f2;
            padding: 20px;
            margin-top: 20px;
        }
    </style>
</head>
<body>

<header>
    <h1>Lyzell'i Keraamikakoda</h1>
    <div class="language-buttons">
        <button onclick="switchLanguage('et')">Eesti</button>
        <button onclick="switchLanguage('en')">English</button>
    </div>
</header>

<nav class="horizontal-menu">
    <a href="#">Home</a>
    <a href="#">Gallery</a>
    <a href="#">Workshops</a>
    <a href="#">Contact</a>
</nav>

<div class="pictures">
    <img src="image1.jpg" alt="Ceramic Work 1">
    <img src="image2.jpg" alt="Ceramic Work 2">
    <img src="image3.jpg" alt="Ceramic Work 3">
</div>

<div class="chat-box">
    <h3>Chat with Us!</h3>
    <p>Feel free to ask us anything.</p>
    
</div>

<footer>
    <p>Company Details:</p>
    <p>Lyzell'i Keraamikakoda OÜ</p>
    <p>1234 Ceramic Street, Tallinn, Estonia</p>
    <p>Email: info@lyzellceramics.ee | Phone: +372 123 4567</p>
</footer>

<script>
    function switchLanguage(language) {
        alert("Switching to " + language + " language. (This functionality will be implemented later.)");
    }
</script>

</body>
</html>

**Comment by Annabell-prog** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lyzell'i Keraamikakoda</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 0;
            margin: 0;
        }
        header {
            text-align: center;
            padding: 20px;
            background-color: #f2f2f2;
        }
        .language-buttons {
            margin-top: 10px;
        }
        .horizontal-menu {
            display: flex;
            justify-content: center;
            padding: 10px;
            background-color: #333;
        }
        .horizontal-menu a {
            color: white;
            text-decoration: none;
            padding: 10px 20px;
        }
        .horizontal-menu a:hover {
            background-color: #575757;
        }
        .pictures {
            display: flex;
            justify-content: space-around;
            margin: 20px;
        }
        .pictures img {
            width: 30%;
            border: 2px solid #ddd;
            padding: 10px;
        }
        .chat-box {
            position: fixed;
            bottom: 20px;
            right: 20px;
            width: 300px;
            height: 400px;
            background-color: #f1f1f1;
            border: 1px solid #ccc;
            border-radius: 10px;
            padding: 10px;
        }
        footer {
            text-align: center;
            background-color: #f2f2f2;
            padding: 20px;
            margin-top: 20px;
        }
    </style>
</head>
<body>

<header>
    <h1>Lyzell'i Keraamikakoda</h1>
    <div class="language-buttons">
        <button onclick="switchLanguage('et')">Eesti</button>
        <button onclick="switchLanguage('en')">English</button>
    </div>
</header>

<nav class="horizontal-menu">
    <a href="#">Home</a>
    <a href="#">Gallery</a>
    <a href="#">Workshops</a>
    <a href="#">Contact</a>
</nav>

<div class="pictures">
    <img src="image1.jpg" alt="Ceramic Work 1">
    <img src="image2.jpg" alt="Ceramic Work 2">
    <img src="image3.jpg" alt="Ceramic Work 3">
</div>

<div class="chat-box">
    <h3>Chat with Us!</h3>
    <p>Feel free to ask us anything.</p>
    
</div>

<footer>
    <p>Company Details:</p>
    <p>Lyzell'i Keraamikakoda OÜ</p>
    <p>1234 Ceramic Street, Tallinn, Estonia</p>
    <p>Email: info@lyzellceramics.ee | Phone: +372 123 4567</p>
</footer>

<script>
    function switchLanguage(language) {
        alert("Switching to " + language + " language. (This functionality will be implemented later.)");
    }
</script>

</body>
</html>

**Comment by Annabell-prog** [comment]
![Uploading Kuvatõmmis 2024-10-17 203136.png…]()

**Comment by OveKre** [comment]
1. The brand name is part of the header and always visible on all pages for clear identification
2. The horizontal menu contains only functional links to available pages. When the user is on a page, the corresponding menu item is highlighted
3. The Instagram logo is visible and functional, directing the user to the correct Instagram profile
4. The Facebook logo is visible and functional, directing the user to the correct Facebook page
5. The images are responsive and displayed without distortion, showcasing different pottery pieces. Clicking on the images leads to the detailed page about the pieces
6. The introductory text is clearly visible on the homepage, setting the tone for the site and guiding users through the main sections
